### ISSUE TITLE
Wei's  milestones

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/admin#4]
- [x] [Tuning Learner](https://github.com/ai-se/tunelearners/milestones)
- [ ] [SMOTE/Tunning on Text Mining](https://github.com/ai-se/SMOTE/milestones)
- [ ] [Caret](https://github.com/ai-se/Caret/milestones)
- [ ] [Written Prelim](https://github.com/ai-se/Wei_prelim-/milestones)
- [ ] [Deep Learning](https://github.com/ai-se/DL/milestones)

==>[REPORT](https://github.com/WeiFoo/Report)

**Comment by WeiFoo** [comment]
https://github.com/WeiFoo/TuningLearners/milestones
