### ISSUE TITLE
George's Milestones

### ISSUE THREAD

**Issue by bigfatnoob** [ai-se/admin#5]
- [ ] [Soft Goals](https://github.com/ai-se/softgoals/milestones).
- [x] [Par GALE](https://github.com/ai-se/parGale/milestones)
- [x] [Thesis](https://github.com/ai-se/George-Thesis/milestones)
- [ ] [Baseline Effort](https://www.sharelatex.com/project/56f94ceb951cdba517a87264)
- [ ] LOC work with Dr Hihn

**Comment by bigfatnoob** [comment]
Shutting down ParGALE. Negative Results

**Comment by timm** [comment]
Stuff to read 
- [ ] software http://borgmoea.org/
- [ ] paper https://goo.gl/dZF1oo

```
@Article{Woodruff2013,
author="Woodruff, Matthew J.
and Reed, Patrick M.
and Simpson, Timothy W.",
title="Many objective visual analytics: rethinking the design of complex engineered systems",
journal="Structural and Multidisciplinary Optimization",
year="2013",
volume="48",
number="1",
pages="201--219",
abstract="Many cognitive and computational challenges accompany the design of complex engineered systems. This study proposes the many-objective visual analytics (MOVA) framework as a new approach to the design of complex engineered systems. MOVA emphasizes learning through problem reformulation, enabled by visual analytics and many-objective search. This study demonstrates insights gained by evolving the formulation of a General Aviation Aircraft (GAA) product family design problem. This problem's considerable complexity and difficulty, along with a history encompassing several formulations, make it well-suited to demonstrate the MOVA framework. The MOVA framework results compare a single objective, a two objective, and a ten objective formulation for optimizing the GAA product family. Highly interactive visual analytics are exploited to demonstrate how decision biases can arise for lower dimensional, highly aggregated problem formulations.",
issn="1615-1488",
doi="10.1007/s00158-013-0891-z",
url="http://dx.doi.org/10.1007/s00158-013-0891-z"
}
```
