### ISSUE TITLE
Jianfeng's milestone

### ISSUE THREAD

**Issue by ginfung** [ai-se/admin#6]
- [ ] [NC Charlotte-privacy sharing](https://github.com/ai-se/privacy_sharing/milestones)
- [ ] [GLAE works?](https://github.com/ai-se/why_GALE_-really-_works/milestones)
- [ ] [surrogate at FM](https://github.com/ai-se/SPL/issues/12)

**Comment by ginfung** [comment]
- [ ] [surrogate](https://github.com/ai-se/surrogate/milestones)
